# Generated by Django 4.2.1 on 2023-05-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_employee_project_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='payment_method',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('onetime', 'Onetime')], default='onetime', max_length=20),
        ),
    ]
