# Generated by Django 4.2.1 on 2023-05-25 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_employee_payment_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='payment_method',
            new_name='payment_type',
        ),
    ]
