# Generated by Django 4.2.1 on 2023-05-25 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_payment_method_employee_payment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('unit', models.CharField(choices=[('cm', 'Cm'), ('lt', 'Lt'), ('kg', 'Kg')], default='kg', max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='quantity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.quantity'),
        ),
    ]
