# Generated by Django 4.2.1 on 2023-05-25 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_quantity_alter_project_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quantity',
            options={'verbose_name': 'Quantity', 'verbose_name_plural': 'Quantities'},
        ),
    ]
