# Generated by Django 4.2.1 on 2023-05-25 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_project_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantity',
            name='unit',
            field=models.CharField(choices=[('cm', 'Cm'), ('lt', 'Lt'), ('kg', 'Kg'), ('peças', 'peças')], default='kg', max_length=5),
        ),
    ]
