# Generated by Django 4.2.1 on 2023-10-15 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_project_budget'),
    ]

    operations = [
        migrations.CreateModel(
            name='FishMeponda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_date', models.DateField()),
                ('sell_date', models.DateField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buy_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_buy_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_sell_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transportation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bags', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transp_handler', models.DecimalField(decimal_places=2, max_digits=10)),
                ('food_handler', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Fish Meponda',
                'verbose_name_plural': 'Fish Meponda',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.quantity')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ingredients', models.ManyToManyField(blank=True, to='app.ingredient')),
            ],
        ),
    ]
