# Generated by Django 4.2.1 on 2023-10-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_recipepreparation_ingredient_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='estimated_sell_price',
            field=models.DecimalField(decimal_places=2, default=150, max_digits=10),
        ),
    ]
